### ISSUE TITLE
i get a error back

### ISSUE THREAD

**Issue by goldjunge91** [GeekyBharat99/Whatsapp-spam-bot-send-messages-on-loop#3]
VM1362:7 Uncaught TypeError: Cannot set properties of undefined (setting 'innerHTML')
    at <anonymous>:7:21
(anonymous) @ VM1362:7
![image](https://user-images.githubusercontent.com/30201929/133888068-95902222-0424-4c8f-bc52-f8118ea317c0.png)

**Comment by GeekyBharat99** [comment]
fixed!!
